.args <- if(interactive()){
  c('./synthetic/data/demo_params.RData')
}else{
  commandArgs(trailingOnly = TRUE)
}


suppressPackageStartupMessages({
  library(tidyverse)
})

# lognorm params (all the sample params except rate_bg_hosp) are desired values 
# converted by convert_to_logmean() and convert_to_logsd() before use

scenario_definitions <-
  tribble(
    ~scenario, ~strain, ~parameter, ~value,
    1, "strain_1", "initial_incidence", "10000",
    1, "strain_1", "exp_growth_rate", "-0.05",
    1, "strain_1", "p_severe", "0.05",
    1, "strain_1", "p_hosp_if_severe", "0.5",
    1, "strain_1", "p_died_if_hosp", "0.1",
    1, "strain_1", "mean_bg_test", "5",
    1, "strain_1", "sd_bg_test", "5",
    1, "strain_1", "rate_bg_hosp", "0.0000005",
    1, "strain_1", "mean_hosp_test", "0.1",
    1, "strain_1", "sd_hosp_test", "2",
    1, "strain_1", "mean_severe", "5",
    1, "strain_1", "sd_severe", "5",
    1, "strain_1", "mean_severe_hosp", "2",
    1, "strain_1", "sd_severe_hosp", "2",
    1, "strain_1", "mean_hosp_died", "10",
    1, "strain_1", "sd_hosp_died", "10",
    1, "strain_1", "mean_resolve", "14",
    1, "strain_1", "sd_resolve", "5",
    1, "strain_2", "initial_incidence", "100",
    1, "strain_2", "exp_growth_rate", "0.05",
    1, "strain_2", "p_severe", "0.05", ## scenario 1: constant CSR ("case severity ratio")
    1, "strain_2", "p_hosp_if_severe", "s1",
    1, "strain_2", "p_died_if_hosp", "0.2",
    1, "strain_2", "mean_bg_test", "s1",
    1, "strain_2", "sd_bg_test", "s1",
    1, "strain_2", "rate_bg_hosp", "s1",
    1, "strain_2", "mean_hosp_test", "s1",
    1, "strain_2", "sd_hosp_test", "s1",
    1, "strain_2", "mean_severe", "s1",
    1, "strain_2", "sd_severe", "s1",
    1, "strain_2", "mean_severe_hosp", "s1",
    1, "strain_2", "sd_severe_hosp", "s1",
    1, "strain_2", "mean_hosp_died", "s1",
    1, "strain_2", "sd_hosp_died", "s1",
    1, "strain_2", "mean_resolve", "s1",
    1, "strain_2", "sd_resolve", "s1",
    2, "strain_1", "initial_incidence", "10000",
    2, "strain_1", "exp_growth_rate", "-0.05",
    2, "strain_1", "p_severe", "0.05",
    2, "strain_1", "p_hosp_if_severe", "0.5",
    2, "strain_1", "p_died_if_hosp", "0.1",
    2, "strain_1", "mean_bg_test", "5",
    2, "strain_1", "sd_bg_test", "5",
    2, "strain_1", "rate_bg_hosp", "0.0000005",
    2, "strain_1", "mean_hosp_test", "0.1",
    2, "strain_1", "sd_hosp_test", "2",
    2, "strain_1", "mean_severe", "5",
    2, "strain_1", "sd_severe", "5",
    2, "strain_1", "mean_severe_hosp", "2",
    2, "strain_1", "sd_severe_hosp", "2",
    2, "strain_1", "mean_hosp_died", "10",
    2, "strain_1", "sd_hosp_died", "10",
    2, "strain_1", "mean_resolve", "14",
    2, "strain_1", "sd_resolve", "5",
    2, "strain_2", "initial_incidence", "100",
    2, "strain_2", "exp_growth_rate", "0.05",
    2, "strain_2", "p_severe", "0.1", ## scenario 2: incoming (growing) strain has double CSR of outgoing strain
    2, "strain_2", "p_hosp_if_severe", "s1",
    2, "strain_2", "p_died_if_hosp", "0.2",
    2, "strain_2", "mean_bg_test", "s1",
    2, "strain_2", "sd_bg_test", "s1",
    2, "strain_2", "rate_bg_hosp", "s1",
    2, "strain_2", "mean_hosp_test", "s1",
    2, "strain_2", "sd_hosp_test", "s1",
    2, "strain_2", "mean_severe", "s1",
    2, "strain_2", "sd_severe", "s1",
    2, "strain_2", "mean_severe_hosp", "s1",
    2, "strain_2", "sd_severe_hosp", "s1",
    2, "strain_2", "mean_hosp_died", "s1",
    2, "strain_2", "sd_hosp_died", "s1",
    2, "strain_2", "mean_resolve", "s1",
    2, "strain_2", "sd_resolve", "s1",
    3, "strain_1", "initial_incidence", "10000",
    3, "strain_1", "exp_growth_rate", "-0.05",
    3, "strain_1", "p_severe", "0.1",
    3, "strain_1", "p_hosp_if_severe", "0.5",
    3, "strain_1", "p_died_if_hosp", "0.1",
    3, "strain_1", "mean_bg_test", "5",
    3, "strain_1", "sd_bg_test", "5",
    3, "strain_1", "rate_bg_hosp", "0.0000005",
    3, "strain_1", "mean_hosp_test", "0.1",
    3, "strain_1", "sd_hosp_test", "2",
    3, "strain_1", "mean_severe", "5",
    3, "strain_1", "sd_severe", "5",
    3, "strain_1", "mean_severe_hosp", "2",
    3, "strain_1", "sd_severe_hosp", "2",
    3, "strain_1", "mean_hosp_died", "10",
    3, "strain_1", "sd_hosp_died", "10",
    3, "strain_1", "mean_resolve", "14",
    3, "strain_1", "sd_resolve", "5",
    3, "strain_2", "initial_incidence", "100",
    3, "strain_2", "exp_growth_rate", "0.05",
    3, "strain_2", "p_severe", "0.05", ## scenario 3: CSR incoming is half of CSR outgoing
    3, "strain_2", "p_hosp_if_severe", "s1",
    3, "strain_2", "p_died_if_hosp", "0.2",
    3, "strain_2", "mean_bg_test", "s1",
    3, "strain_2", "sd_bg_test", "s1",
    3, "strain_2", "rate_bg_hosp", "s1",
    3, "strain_2", "mean_hosp_test", "s1",
    3, "strain_2", "sd_hosp_test", "s1",
    3, "strain_2", "mean_severe", "s1",
    3, "strain_2", "sd_severe", "s1",
    3, "strain_2", "mean_severe_hosp", "s1",
    3, "strain_2", "sd_severe_hosp", "s1",
    3, "strain_2", "mean_hosp_died", "s1",
    3, "strain_2", "sd_hosp_died", "s1",
    3, "strain_2", "mean_resolve", "s1",
    3, "strain_2", "sd_resolve", "s1",
    4, "strain_1", "initial_incidence", "10000",
    4, "strain_1", "exp_growth_rate", "-0.05",
    4, "strain_1", "p_severe", "0.05",
    4, "strain_1", "p_hosp_if_severe", "0.5",
    4, "strain_1", "p_died_if_hosp", "0.1",
    4, "strain_1", "mean_bg_test", "5",
    4, "strain_1", "sd_bg_test", "5",
    4, "strain_1", "rate_bg_hosp", "0.0000005",
    4, "strain_1", "mean_hosp_test", "0.1",
    4, "strain_1", "sd_hosp_test", "2",
    4, "strain_1", "mean_severe", "5",
    4, "strain_1", "sd_severe", "5",
    4, "strain_1", "mean_severe_hosp", "2",
    4, "strain_1", "sd_severe_hosp", "2",
    4, "strain_1", "mean_hosp_died", "10",
    4, "strain_1", "sd_hosp_died", "10",
    4, "strain_1", "mean_resolve", "14",
    4, "strain_1", "sd_resolve", "5",
    4, "strain_2", "initial_incidence", "100",
    4, "strain_2", "exp_growth_rate", "0.05",
    4, "strain_2", "p_severe", "0.05", ## scenario 4: CSR same for both strains but lower primary detection probability for strain 2 (currently implemented simplistically as lower rate of bg testing)
    4, "strain_2", "p_hosp_if_severe", "s1",
    4, "strain_2", "p_died_if_hosp", "0.2",
    4, "strain_2", "mean_bg_test", "10",
    4, "strain_2", "sd_bg_test", "10",
    4, "strain_2", "rate_bg_hosp", "s1",
    4, "strain_2", "mean_hosp_test", "s1",
    4, "strain_2", "sd_hosp_test", "s1",
    4, "strain_2", "mean_severe", "s1",
    4, "strain_2", "sd_severe", "s1",
    4, "strain_2", "mean_severe_hosp", "s1",
    4, "strain_2", "sd_severe_hosp", "s1",
    4, "strain_2", "mean_hosp_died", "s1",
    4, "strain_2", "sd_hosp_died", "s1",
    4, "strain_2", "mean_resolve", "s1",
    4, "strain_2", "sd_resolve", "s1",
    5, "strain_1", "initial_incidence", "10000",
    5, "strain_1", "exp_growth_rate", "-0.05",
    5, "strain_1", "p_severe", "0.05",
    5, "strain_1", "p_hosp_if_severe", "0.5",
    5, "strain_1", "p_died_if_hosp", "0.1",
    5, "strain_1", "mean_bg_test", "5",
    5, "strain_1", "sd_bg_test", "5",
    5, "strain_1", "rate_bg_hosp", "0.0000005",
    5, "strain_1", "mean_hosp_test", "0.1",
    5, "strain_1", "sd_hosp_test", "2",
    5, "strain_1", "mean_severe", "5",
    5, "strain_1", "sd_severe", "5",
    5, "strain_1", "mean_severe_hosp", "2",
    5, "strain_1", "sd_severe_hosp", "2",
    5, "strain_1", "mean_hosp_died", "10",
    5, "strain_1", "sd_hosp_died", "10",
    5, "strain_1", "mean_resolve", "14",
    5, "strain_1", "sd_resolve", "5",
    5, "strain_2", "initial_incidence", "100",
    5, "strain_2", "exp_growth_rate", "0.05",
    5, "strain_2", "p_severe", "0.1", ## scenario 5: CSR incoming is double of CSR outgoing, primary detection probability is higher for incoming strain (currently just via shorter mean_bg_test and smaller sd_bg_test)
    5, "strain_2", "p_hosp_if_severe", "s1",
    5, "strain_2", "p_died_if_hosp", "0.2",
    5, "strain_2", "mean_bg_test", "2",
    5, "strain_2", "sd_bg_test", "2",
    5, "strain_2", "rate_bg_hosp", "s1",
    5, "strain_2", "mean_hosp_test", "s1",
    5, "strain_2", "sd_hosp_test", "s1",
    5, "strain_2", "mean_severe", "s1",
    5, "strain_2", "sd_severe", "s1",
    5, "strain_2", "mean_severe_hosp", "s1",
    5, "strain_2", "sd_severe_hosp", "s1",
    5, "strain_2", "mean_hosp_died", "s1",
    5, "strain_2", "sd_hosp_died", "s1",
    5, "strain_2", "mean_resolve", "s1",
    5, "strain_2", "sd_resolve", "s1"
  )

param_table_wide <- scenario_definitions %>%
  relocate(parameter, .before = strain) %>%
  unite("param", parameter:strain) %>%
  pivot_wider(id_cols = scenario, names_from = param, values_from = value)


param_table <- param_table_wide %>%
  rowwise() %>% ##close your eyes!
  mutate(
    p_severe_strain_2 = ifelse(p_severe_strain_2 == "s1", p_severe_strain_1, p_severe_strain_2),
    p_hosp_if_severe_strain_2 = ifelse(p_hosp_if_severe_strain_2 == "s1", p_hosp_if_severe_strain_1, p_hosp_if_severe_strain_2),
    p_died_if_hosp_strain_2 = ifelse(p_died_if_hosp_strain_2 == "s1", p_died_if_hosp_strain_1, p_died_if_hosp_strain_2),
    mean_bg_test_strain_2 = ifelse(mean_bg_test_strain_2 == "s1", mean_bg_test_strain_1, mean_bg_test_strain_2),
    sd_bg_test_strain_2 = ifelse(sd_bg_test_strain_2 == "s1", sd_bg_test_strain_1, sd_bg_test_strain_2),
    rate_bg_hosp_strain_2 = ifelse(rate_bg_hosp_strain_2 == "s1", rate_bg_hosp_strain_1, rate_bg_hosp_strain_2),
    mean_hosp_test_strain_2 = ifelse(mean_hosp_test_strain_2 == "s1", mean_hosp_test_strain_1, mean_hosp_test_strain_2),
    sd_hosp_test_strain_2 = ifelse(sd_hosp_test_strain_2 == "s1", sd_hosp_test_strain_1, sd_hosp_test_strain_2),
    mean_severe_strain_2 = ifelse(mean_severe_strain_2 == "s1", mean_severe_strain_1, mean_severe_strain_2),
    sd_severe_strain_2 = ifelse(sd_severe_strain_2 == "s1", sd_severe_strain_1, sd_severe_strain_2),
    mean_severe_hosp_strain_2 = ifelse(mean_severe_hosp_strain_2 == "s1", mean_severe_hosp_strain_1, mean_severe_hosp_strain_2),
    sd_severe_hosp_strain_2 = ifelse(sd_severe_hosp_strain_2 == "s1", sd_severe_hosp_strain_1, sd_severe_hosp_strain_2),
    mean_hosp_died_strain_2 = ifelse(mean_hosp_died_strain_2 == "s1", mean_hosp_died_strain_1, mean_hosp_died_strain_2),
    sd_hosp_died_strain_2 = ifelse(sd_hosp_died_strain_2 == "s1", sd_hosp_died_strain_1, sd_hosp_died_strain_2),
    mean_resolve_strain_2 = ifelse(mean_resolve_strain_2 == "s1", mean_resolve_strain_1, mean_resolve_strain_2),
    sd_resolve_strain_2 = ifelse(sd_resolve_strain_2 == "s1", sd_resolve_strain_1, sd_resolve_strain_2)
  ) %>% 
  ungroup() %>%
  mutate(across(everything(), ~ as.numeric(.x)))


save(param_table, file = tail(.args, 1))
